import React, { useState } from 'react';
import { buildPrompts } from './dream100Prompts';

/**
 * Dream100Output — rendered after generation completes.
 * Shows output header, action buttons (copy all, email, download, restart),
 * 7 collapsible phase cards, NurturInk CTA, share strip.
 */
export default function Dream100Output({ formData, onRestart }) {
  const prompts = buildPrompts(formData);
  const [emailModalOpen, setEmailModalOpen] = useState(false);
  const [copyAllDone, setCopyAllDone] = useState(false);

  // ─── Helpers ─────────────────────────────────────────────
  const copyAll = () => {
    const header = `DREAM 100 PARTNER BLUEPRINT\n${formData.niche} | ${formData.geo}\nGenerated by NurturInk — pipeline.nurturink.com\n\n`;
    const body = prompts.map((p, i) =>
      `${'═'.repeat(44)}\nPHASE ${i + 1}: ${p.title}\nOptimized for: ${p.model}\n${'═'.repeat(44)}\n\n${p.prompt}`
    ).join('\n\n\n');
    navigator.clipboard.writeText(header + body).then(() => {
      setCopyAllDone(true);
      setTimeout(() => setCopyAllDone(false), 3000);
    });
  };

  const downloadAll = () => {
    const header = `DREAM 100 PARTNER BLUEPRINT\n${formData.niche} | ${formData.geo}\nGenerated for: ${formData.name}\nGenerated by NurturInk — pipeline.nurturink.com\nLearn how NurturInk helps agents stand out: nurturink.com/realestate\n\n`;
    const body = prompts.map((p, i) =>
      `${'═'.repeat(50)}\nPHASE ${i + 1}: ${p.title}\nOptimized for: ${p.model}\n${'═'.repeat(50)}\n\n${p.prompt}`
    ).join('\n\n\n');
    const blob = new Blob([header + body], { type: 'text/plain' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = `Dream100-Blueprint-${(formData.niche||'').replace(/[^a-z0-9]/gi,'-')}-${(formData.geo||'').replace(/[^a-z0-9]/gi,'-')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const shareApp = () => {
    const url  = 'https://pipeline.nurturink.com';
    const text = 'Just built my Dream 100 referral partner blueprint using this free tool from NurturInk. Takes 3 minutes. 7 AI prompts. No login. Try it:';
    if (navigator.share) {
      navigator.share({ title: 'Dream 100 Blueprint Builder', text, url });
    } else {
      navigator.clipboard.writeText(`${text} ${url}`).then(() => alert('Share link copied to clipboard!'));
    }
  };

  return (
    <div style={{ maxWidth: 600, margin: '0 auto', padding: '28px 18px 80px', animation: 'd100-fadeUp 0.25s ease both' }}>

      {/* Output header */}
      <div style={{
        textAlign: 'center', marginBottom: 28,
        paddingBottom: 24, borderBottom: '1px solid var(--d100-border)',
      }}>
        <div style={{
          display: 'inline-block',
          background: 'rgba(45,106,79,0.1)', color: 'var(--d100-success)',
          fontSize: 12, fontWeight: 700, letterSpacing: '0.06em', textTransform: 'uppercase',
          padding: '5px 14px', borderRadius: 20, marginBottom: 14,
        }}>✓ Your Blueprint is Ready</div>
        <h1 style={{ fontSize: 22, fontWeight: 800, color: 'var(--d100-navy)', marginBottom: 8, lineHeight: 1.25, letterSpacing: '-0.01em' }}>
          Your {formData.nicheBase || formData.niche} Dream 100 Blueprint
        </h1>
        <p style={{ fontSize: 15, color: 'var(--d100-text-muted)', lineHeight: 1.5 }}>
          {formData.name} · {formData.niche} · {formData.geo}
        </p>
      </div>

      {/* Action buttons */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 10, marginBottom: 28 }}>
        <button
          onClick={copyAll}
          style={{
            width: '100%', padding: 15,
            background: copyAllDone ? 'var(--d100-success)' : 'var(--d100-navy)',
            color: 'var(--d100-white)', border: 'none',
            borderRadius: 10, fontFamily: "'Sora', sans-serif",
            fontSize: 16, fontWeight: 700, cursor: 'pointer', transition: 'all 0.2s',
          }}
        >
          {copyAllDone ? '✓ All 7 Prompts Copied!' : '📋 Copy All 7 Prompts'}
        </button>
        <div style={{ display: 'flex', gap: 10 }}>
          <button
            onClick={() => setEmailModalOpen(true)}
            style={outlineBtn}
          >✉ Email Me This</button>
          <button
            onClick={downloadAll}
            style={{ ...outlineBtn, borderColor: 'var(--d100-gold)', color: 'var(--d100-gold)' }}
          >⬇ Download All</button>
          <button
            onClick={onRestart}
            style={{ ...outlineBtn, color: 'var(--d100-text-muted)', minWidth: 44 }}
          >↺</button>
        </div>
      </div>

      {/* Phase cards */}
      {prompts.map((phase, i) => (
        <PhaseCard key={i} phase={phase} index={i} />
      ))}

      {/* NurturInk CTA */}
      <NurturinkCTA />

      {/* Share strip */}
      <div style={{ textAlign: 'center', padding: 16, fontSize: 14, color: 'var(--d100-text-muted)', fontWeight: 500, lineHeight: 1.5 }}>
        Know another agent who needs this?<br />
        <span
          onClick={shareApp}
          style={{ color: 'var(--d100-gold)', fontWeight: 700, cursor: 'pointer', display: 'inline-block', marginTop: 4 }}
        >
          Share this free tool →
        </span>
      </div>

      {/* Email modal */}
      {emailModalOpen && <EmailModal formData={formData} prompts={prompts} onClose={() => setEmailModalOpen(false)} />}
    </div>
  );
}

// ─── Phase Card ─────────────────────────────────────────
function PhaseCard({ phase, index }) {
  const [open, setOpen] = useState(index === 0);
  const [copied, setCopied] = useState(false);

  const copyPhase = () => {
    navigator.clipboard.writeText(phase.prompt).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  };

  const downloadPhase = () => {
    const content = `DREAM 100 BLUEPRINT — Phase ${index + 1}: ${phase.title}\nOptimized for: ${phase.model}\nGenerated by NurturInk — pipeline.nurturink.com\n\n${'═'.repeat(50)}\n\n${phase.prompt}\n\n${'═'.repeat(50)}\nLearn how NurturInk helps agents stand out: nurturink.com/realestate`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = `Dream100-Phase${index + 1}-${phase.title.replace(/[^a-z0-9]/gi, '-')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{
      background: 'var(--d100-white)',
      borderRadius: 'var(--d100-radius)',
      border: '1px solid var(--d100-border)',
      borderLeft: '4px solid var(--d100-gold)',
      marginBottom: 14,
      boxShadow: 'var(--d100-shadow)',
      overflow: 'hidden',
    }}>
      {/* Header (clickable) */}
      <div
        onClick={() => setOpen(o => !o)}
        style={{
          padding: '16px 18px 14px',
          display: 'flex', alignItems: 'flex-start',
          justifyContent: 'space-between', gap: 12,
          cursor: 'pointer', userSelect: 'none',
        }}
      >
        <div style={{ flex: 1 }}>
          <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', color: 'var(--d100-gold)', marginBottom: 3 }}>
            Phase {index + 1} of 7
          </div>
          <div style={{ fontSize: 16, fontWeight: 700, color: 'var(--d100-navy)', lineHeight: 1.3 }}>{phase.title}</div>
          <span style={{
            display: 'inline-block', fontSize: 11, fontWeight: 600,
            padding: '3px 9px', borderRadius: 12,
            background: 'rgba(27,42,74,0.07)', color: 'var(--d100-navy)', marginTop: 5,
          }}>{phase.model}</span>
        </div>
        <div style={{
          color: 'var(--d100-text-muted)', fontSize: 20,
          transition: 'transform 0.25s', flexShrink: 0, marginTop: 2, lineHeight: 1,
          transform: open ? 'rotate(180deg)' : 'rotate(0deg)',
        }}>⌄</div>
      </div>

      {/* Body */}
      {open && (
        <div style={{ padding: '0 18px 18px', borderTop: '1px solid var(--d100-border)' }}>
          <p style={{
            fontSize: 13, color: 'var(--d100-text-muted)', fontStyle: 'italic',
            padding: '10px 0 12px', borderBottom: '1px dashed var(--d100-border)',
            marginBottom: 14, lineHeight: 1.5,
          }}>{phase.modelNote}</p>
          <div className="d100-prompt-text" style={{
            background: 'var(--d100-cream)',
            border: '1px solid var(--d100-border)',
            borderRadius: 8, padding: 16,
            fontSize: 14, lineHeight: 1.75, color: 'var(--d100-text)',
            whiteSpace: 'pre-wrap', fontFamily: "'Sora', sans-serif",
            maxHeight: 320, overflowY: 'auto', fontWeight: 400,
          }}>{phase.prompt}</div>
          <div style={{ display: 'flex', gap: 8, marginTop: 12 }}>
            <button
              onClick={copyPhase}
              style={{
                flex: 1, padding: 12,
                background: copied ? 'var(--d100-success)' : 'var(--d100-cream)',
                border: `1.5px solid ${copied ? 'var(--d100-success)' : 'var(--d100-border)'}`,
                borderRadius: 8, fontFamily: "'Sora', sans-serif",
                fontSize: 14, fontWeight: 700,
                color: copied ? 'var(--d100-white)' : 'var(--d100-navy)',
                cursor: 'pointer', transition: 'all 0.2s',
              }}
            >{copied ? '✓ Copied!' : '📋 Copy'}</button>
            <button
              onClick={downloadPhase}
              style={{
                padding: '12px 14px',
                background: 'var(--d100-cream)',
                border: '1.5px solid var(--d100-border)',
                borderRadius: 8, fontFamily: "'Sora', sans-serif",
                fontSize: 13, fontWeight: 700, color: 'var(--d100-navy)',
                cursor: 'pointer', transition: 'all 0.2s', whiteSpace: 'nowrap', flexShrink: 0,
              }}
            >⬇ Download</button>
          </div>
        </div>
      )}
    </div>
  );
}

// ─── NurturInk CTA ───────────────────────────────────────
function NurturinkCTA() {
  return (
    <div style={{
      background: 'var(--d100-navy)', borderRadius: 'var(--d100-radius)',
      padding: '28px 22px', margin: '28px 0',
      position: 'relative', overflow: 'hidden',
    }}>
      {/* Radial accent */}
      <div style={{
        position: 'absolute', top: -30, right: -30,
        width: 160, height: 160,
        background: 'radial-gradient(circle, rgba(201,151,58,0.14), transparent 65%)',
        pointerEvents: 'none',
      }} />
      <div style={{ position: 'relative', zIndex: 1 }}>
        <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.09em', textTransform: 'uppercase', color: 'var(--d100-gold-light)', marginBottom: 10 }}>
          Brought to you by NurturInk
        </div>
        <h3 style={{ fontSize: 20, fontWeight: 800, color: 'var(--d100-white)', marginBottom: 14, lineHeight: 1.3, letterSpacing: '-0.01em' }}>
          The One Move That Gets These Partners to Actually Respond
        </h3>
        <p style={{ fontSize: 15, color: 'rgba(255,255,255,0.85)', lineHeight: 1.65, marginBottom: 14, fontWeight: 400 }}>
          You've got your Dream 10 list. Most agents will email them — and it'll get buried. A few will call — and it'll go to voicemail.
        </p>
        <p style={{ fontSize: 15, color: 'rgba(255,255,255,0.85)', lineHeight: 1.65, marginBottom: 14, fontWeight: 400 }}>
          <strong style={{ color: '#fff', fontWeight: 700 }}>The agents who stand out send a handwritten note first.</strong> Not because it's fancy — because it's the only thing guaranteed to get opened and read. When a mortgage broker gets a real handwritten card from you, they remember it. The next time a client needs an agent, they call you.
        </p>
        <p style={{ fontSize: 15, color: 'rgba(255,255,255,0.85)', lineHeight: 1.65, marginBottom: 22, fontWeight: 400 }}>
          NurturInk automates this. <strong style={{ color: '#fff', fontWeight: 700 }}>Real ballpoint pen. Real paper. Your signature. From $2 a card.</strong> No subscription required.
        </p>

        {/* Stats bar */}
        <div style={{
          display: 'flex', marginBottom: 22,
          background: 'rgba(255,255,255,0.06)', borderRadius: 10, overflow: 'hidden',
          border: '1px solid rgba(255,255,255,0.1)',
        }}>
          {[
            { stat: '99%', label: 'open rate on physical mail' },
            { stat: '$2',  label: 'per card, no subscription' },
            { stat: '3–5×', label: 'higher response vs email' },
          ].map((s, i, arr) => (
            <div key={i} style={{
              flex: 1, padding: '13px 8px', textAlign: 'center',
              borderRight: i < arr.length - 1 ? '1px solid rgba(255,255,255,0.08)' : 'none',
            }}>
              <strong style={{ display: 'block', fontSize: 20, color: 'var(--d100-gold-light)', fontWeight: 800, lineHeight: 1, marginBottom: 3, letterSpacing: '-0.01em' }}>{s.stat}</strong>
              <span style={{ fontSize: 11, color: 'rgba(255,255,255,0.5)', fontWeight: 400, lineHeight: 1.3, display: 'block' }}>{s.label}</span>
            </div>
          ))}
        </div>

        {/* CTA link */}
        <a
          href="https://nurturink.com/realestate"
          target="_blank"
          rel="noreferrer"
          style={{
            display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8,
            background: 'var(--d100-gold)', color: 'var(--d100-navy)',
            textDecoration: 'none', fontWeight: 800, fontSize: 15,
            padding: 14, borderRadius: 10, transition: 'all 0.2s', width: '100%',
          }}
          onMouseEnter={e => { e.currentTarget.style.background = 'var(--d100-gold-light)'; }}
          onMouseLeave={e => { e.currentTarget.style.background = 'var(--d100-gold)'; }}
        >
          See How NurturInk Works →
        </a>
      </div>
    </div>
  );
}

// ─── Email Modal ─────────────────────────────────────────
function EmailModal({ formData, prompts, onClose }) {
  const [email, setEmail] = useState('');
  const [emailError, setEmailError] = useState(false);
  const [sent, setSent] = useState(false);

  const send = () => {
    if (!email || !email.includes('@')) { setEmailError(true); return; }
    const subject  = encodeURIComponent(`Your Dream 100 Blueprint — ${formData.niche} in ${formData.geo}`);
    const bodyText = `Hi ${formData.name},\n\nHere is your Dream 100 Partner Blueprint for ${formData.niche} in ${formData.geo}.\n\n`
      + prompts.map((p, i) => `PHASE ${i + 1}: ${p.title}\nFor: ${p.model}\n\n${p.prompt}`).join('\n\n---\n\n')
      + `\n\n---\nGenerated by NurturInk Dream 100 Builder\nhttps://pipeline.nurturink.com\n\nLearn how NurturInk can help you land these partners:\nhttps://nurturink.com/realestate`;
    window.open(`mailto:${email}?subject=${subject}&body=${encodeURIComponent(bodyText)}`);
    setSent(true);
  };

  return (
    <div
      onClick={e => { if (e.target === e.currentTarget) onClose(); }}
      style={{
        position: 'fixed', inset: 0,
        background: 'rgba(15,20,40,0.6)', backdropFilter: 'blur(5px)',
        zIndex: 200, display: 'flex', alignItems: 'flex-end', justifyContent: 'center',
      }}
    >
      <div style={{
        background: 'var(--d100-white)',
        borderRadius: '20px 20px 0 0',
        padding: '28px 22px 36px',
        width: '100%', maxWidth: 600,
        boxShadow: 'var(--d100-shadow-lg)',
        animation: 'd100-slideUp 0.28s ease both',
      }}>
        {/* Handle */}
        <div style={{ width: 36, height: 4, background: 'var(--d100-border)', borderRadius: 2, margin: '0 auto 20px' }} />

        {!sent ? (
          <>
            <h3 style={{ fontSize: 20, fontWeight: 800, color: 'var(--d100-navy)', marginBottom: 6 }}>Email Me My Blueprint</h3>
            <p style={{ fontSize: 15, color: 'var(--d100-text-muted)', marginBottom: 18, lineHeight: 1.5 }}>
              We'll send your complete 7-phase blueprint to your inbox. No spam — one email, just your blueprint.
            </p>
            <input
              type="email" value={email}
              onChange={e => { setEmail(e.target.value); setEmailError(false); }}
              placeholder="your@email.com"
              style={{
                width: '100%', padding: '14px 16px',
                border: `1.5px solid ${emailError ? '#DC2626' : 'var(--d100-border)'}`,
                borderRadius: 10, fontFamily: "'Sora', sans-serif", fontSize: 16,
                color: 'var(--d100-text)', background: 'var(--d100-cream)',
                outline: 'none', marginBottom: 12,
              }}
            />
            <button
              onClick={send}
              style={{
                width: '100%', padding: 15,
                background: 'var(--d100-gold)', color: 'var(--d100-navy)', border: 'none',
                borderRadius: 10, fontFamily: "'Sora', sans-serif",
                fontSize: 16, fontWeight: 800, cursor: 'pointer', marginBottom: 10,
              }}
            >Send My Blueprint</button>
            <button onClick={onClose} style={{
              width: '100%', padding: 13,
              border: '1.5px solid var(--d100-border)', background: 'transparent',
              borderRadius: 10, fontFamily: "'Sora', sans-serif",
              fontSize: 15, color: 'var(--d100-text-muted)', cursor: 'pointer', fontWeight: 500,
            }}>Cancel</button>
            <p style={{ fontSize: 11, color: 'var(--d100-text-muted)', textAlign: 'center', marginTop: 10, lineHeight: 1.5 }}>
              Your email is used only to deliver your blueprint. We may occasionally share helpful resources from NurturInk. Unsubscribe anytime.
            </p>
          </>
        ) : (
          <div style={{ textAlign: 'center', padding: '12px 0' }}>
            <div style={{ fontSize: 44, marginBottom: 14 }}>✉️</div>
            <h3 style={{ fontSize: 20, fontWeight: 800, color: 'var(--d100-navy)', marginBottom: 8 }}>Check Your Inbox</h3>
            <p style={{ fontSize: 15, color: 'var(--d100-text-muted)', marginBottom: 20, lineHeight: 1.5 }}>
              Your blueprint is on its way. While you're here — see how NurturInk can help you land those partners faster.
            </p>
            <a href="https://nurturink.com/realestate" target="_blank" rel="noreferrer" style={{
              display: 'block', background: 'var(--d100-gold)', color: 'var(--d100-navy)',
              textDecoration: 'none', fontWeight: 800, fontSize: 15,
              padding: 14, borderRadius: 10, marginBottom: 12,
            }}>See NurturInk for Agents →</a>
            <button onClick={onClose} style={{
              width: '100%', padding: 13,
              border: '1.5px solid var(--d100-border)', background: 'transparent',
              borderRadius: 10, fontFamily: "'Sora', sans-serif",
              fontSize: 15, color: 'var(--d100-text-muted)', cursor: 'pointer', fontWeight: 500,
            }}>Close</button>
          </div>
        )}
      </div>
    </div>
  );
}

// ─── Shared styles ────────────────────────────────────────
const outlineBtn = {
  flex: 1, padding: 13, background: 'transparent',
  color: 'var(--d100-navy)', border: '1.5px solid var(--d100-navy)',
  borderRadius: 10, fontFamily: "'Sora', sans-serif",
  fontSize: 15, fontWeight: 600, cursor: 'pointer', transition: 'all 0.2s',
};